# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 23:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('born', models.CharField(max_length=100)),
                ('live_in', models.CharField(max_length=100)),
                ('native_languages', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='This field must be a integers list', regex='^[1-8](,[1-8])*$')])),
                ('languages_speak', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='This field must be a integers list', regex='^[1-8](,[1-8])*$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
