# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppricedetail',
            name='hour_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD) per hour'),
        ),
        migrations.AlterField(
            model_name='privatepricedetail',
            name='hour_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD) per hour'),
        ),
    ]
