# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersion',
            name='other_category',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
