# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20170110_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='immersion',
            name='other_category',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='methodology',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
