# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20161120_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address_details_live_in',
        ),
    ]
