# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20170110_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='institution',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_study',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='born',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
