# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20170111_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
