# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20170115_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('VA', 'validated'), ('VE', 'verified')], default='NW', max_length=2),
        ),
    ]
