# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='validated',
        ),
    ]
