# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_remove_teacher_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='recommended',
            field=models.IntegerField(null=True),
        ),
    ]
