# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20170131_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grouppricedetail',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='immersion',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='privatepricedetail',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
