# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_auto_20170212_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='user_account',
        ),
    ]
