# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_auto_20170212_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_account',
            new_name='user',
        ),
    ]
