# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_auto_20170214_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='immersion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immersion', to='teachers.Immersion'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='languages',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='teachers.Language'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='teachers.Price'),
        ),
    ]
