# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_auto_20170215_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='born',
        ),
        migrations.AddField(
            model_name='profile',
            name='born_city',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='profile',
            name='born_country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
