# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_auto_20170217_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='location',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.Profile'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
