# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_auto_20170217_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='teachers.Language'),
        ),
    ]
