# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=110, verbose_name='Location City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=2, verbose_name='Location Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='locations.Position', verbose_name='Position on Google Map'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=110, verbose_name='Location State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Location ZipCode'),
        ),
        migrations.AlterField(
            model_name='position',
            name='lat',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='latitude on Google Map'),
        ),
        migrations.AlterField(
            model_name='position',
            name='lng',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Longitude on Google Map'),
        ),
    ]
