# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20170207_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='locations.Position'),
        ),
    ]
