# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_es',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
