# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20170410_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
