# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_merge_20170131_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
