# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20170207_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='next_feature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
