# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedback_next_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='uid',
        ),
    ]
