# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_remove_feedback_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='next_other_feature',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
