# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='early',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
