# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0002_auto_20161108_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
