# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0003_auto_20161108_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='early',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='early',
            name='last_name',
        ),
        migrations.AddField(
            model_name='early',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
