# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0006_auto_20161108_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='early',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='early',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
