# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0007_auto_20170115_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early',
            name='first_name',
            field=models.CharField(default='*', max_length=100),
        ),
        migrations.AlterField(
            model_name='early',
            name='last_name',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
