# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0008_auto_20170115_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='early',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
