# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0009_early_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
