# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0010_auto_20170131_1953'),
        ('early', '0010_auto_20170131_2141'),
    ]

    operations = [
    ]
