# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early', '0012_auto_20170207_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='early',
            name='uid',
        ),
    ]
