# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 02:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_profile_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Type of Accommodation')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Accommodation Price')),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Amenities')),
                ('other_amenities', models.TextField(blank=True, max_length=5000, verbose_name='Other Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Options')),
                ('other_option', models.TextField(blank=True, max_length=5000, verbose_name='Other Amenities')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Value of Booking Fee (USD)')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Options')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGeneralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD)')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='Hours')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
                ('student', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), blank=True, size=None, verbose_name='Amount of Student per Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupIntensiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD)')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='Hours')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
                ('student', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), blank=True, size=None, verbose_name='Amount of Student per Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Immersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('option', multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name='Immersion options')),
                ('other_option', models.TextField(blank=True, max_length=5000, verbose_name='Other Immersion')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
            ],
        ),
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Package Name')),
                ('description', models.TextField(blank=True, default='', max_length=10000, verbose_name='Description')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Package Price (USD)')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('methods', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Visa'), (1, 'Mastercard'), (2, 'Paypal'), (3, 'Cash')], max_length=7, verbose_name='Payment Methods Accepted')),
                ('other', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Other Payment Methods')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='schools.GroupClass', verbose_name='Group Classes')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateGeneralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD)')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='Hours')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateIntensiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Price (USD)')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='Hours')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(blank=True, default='', max_length=5000, verbose_name='School Photo')),
                ('name', models.CharField(default='', max_length=100, verbose_name='School Name')),
                ('about', models.TextField(blank=True, default='', max_length=10000, verbose_name='About School')),
                ('language_teach', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Languages Teach')),
                ('website', models.CharField(default='', max_length=200, verbose_name='Website')),
                ('facebook', models.CharField(default='', max_length=200, verbose_name='Facebook')),
                ('twitter', models.CharField(default='', max_length=200, verbose_name='Twitter')),
                ('instagram', models.CharField(default='', max_length=200, verbose_name='Instagram')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('facebook_group', models.CharField(default='', max_length=200, verbose_name='Group on Facebook')),
                ('meetup_group', models.CharField(default='', max_length=200, verbose_name='Group on Meetup.com')),
                ('language_exchange', models.BooleanField(default=False, verbose_name='Language Exchange')),
                ('atmosphere', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Atmosphere')),
                ('classes_begin', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13, verbose_name='Classes Begin')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='schools.Accommodation', verbose_name='Accommodation')),
                ('amenities', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='schools.Amenities', verbose_name='Amenities')),
                ('booking_fee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_fee', to='schools.BookingFee', verbose_name='Booking Fee')),
                ('discount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='schools.Discount', verbose_name='Discounts')),
                ('immersion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immersion', to='schools.Immersion', verbose_name='Immersion')),
                ('package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='schools.Package', verbose_name='Packages')),
                ('payment_method', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='schools.PaymentMethod', verbose_name='Payment Methods')),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='schools.Price', verbose_name='Prices')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Options')),
                ('city_tour', models.BooleanField(default=False, verbose_name='City Tour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Options')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExchangeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='YES/NO')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Work Exchange Categories')),
                ('terms', models.TextField(blank=True, max_length=5000, verbose_name='Terms, Details or more information')),
            ],
        ),
        migrations.AddField(
            model_name='workexchange',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.WorkExchangeOption', verbose_name='Work Exchange Options'),
        ),
        migrations.AddField(
            model_name='school',
            name='tour',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='schools.Tour', verbose_name='Tours'),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='School Manager'),
        ),
        migrations.AddField(
            model_name='school',
            name='volunteering',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteering', to='schools.Volunteering', verbose_name='Volunteering'),
        ),
        migrations.AddField(
            model_name='school',
            name='work_exchange',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_exchange', to='schools.WorkExchange', verbose_name='Work Exchange'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='general_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_general_type', to='schools.PrivateGeneralType', verbose_name='General Classes'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='intensive_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_intensive_type', to='schools.PrivateIntensiveType', verbose_name='Intensive Classes'),
        ),
        migrations.AddField(
            model_name='price',
            name='private',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private', to='schools.PrivateClass', verbose_name='Private Classes'),
        ),
        migrations.AddField(
            model_name='package',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.PackageOption', verbose_name='Package Options'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='general_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_type', to='schools.GroupGeneralType', verbose_name='General Classes'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='intensive_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intensive_type', to='schools.GroupIntensiveType', verbose_name='Intensive Classes'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.AccommodationOption', verbose_name='Accommodation Options'),
        ),
    ]
