# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 02:06
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immersion',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Games and activities with local'), (1, 'Coffee tasting experience'), (2, 'Beer tasting experience'), (3, 'Chocolate tasting experience'), (4, 'Pub crawl'), (5, 'Local food tasting'), (6, 'Local dance class')], max_length=13, verbose_name='Immersion options'),
        ),
    ]
