# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 21:05
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Visa'), (1, 'Mastercard'), (2, 'Paypal'), (3, 'Cash')], max_length=7),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes_begin',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13),
        ),
    ]
