# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 06:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgeneraltype',
            name='student',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), blank=True, help_text='Use follow format: minimum value, maximum value', size=2, verbose_name='Amount of Student per Group'),
        ),
        migrations.AlterField(
            model_name='groupintensivetype',
            name='student',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), blank=True, help_text='Use follow format: minimum value, maximum value', size=2, verbose_name='Amount of Student per Group'),
        ),
    ]
