# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 02:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20170316_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Wireless Internet'), (2, 'Laptop friendly workspace'), (3, 'Air conditioning'), (4, 'Heating'), (5, 'Breakfast'), (6, 'Lunch'), (7, 'Dinner'), (8, 'Snack'), (9, 'Coffee'), (10, 'Tea'), (11, 'Hammocks'), (12, 'Classrooms'), (13, 'Computers room'), (14, 'Video projector'), (15, 'Lounge area')], max_length=35, verbose_name='Amenities options'),
        ),
        migrations.AlterField(
            model_name='immersion',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Games and activities with local'), (2, 'Coffee tasting experience'), (3, 'Beer tasting experience'), (4, 'Chocolate tasting experience'), (5, 'Pub crawl'), (6, 'Local food tasting'), (7, 'Local dance class')], max_length=13, verbose_name='Immersion options'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Paypal'), (4, 'Cash')], max_length=7, verbose_name='Payment Methods Accepted'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes_begin',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13, verbose_name='Classes Begin'),
        ),
    ]
