# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20170315_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='immersion',
        ),
        migrations.AddField(
            model_name='immersion',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schools.School'),
        ),
    ]
