# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 03:20
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20170316_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoption',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Private room'), (2, 'Shared room'), (3, 'Private bathroom'), (4, 'Breakfast'), (5, 'Lunch'), (6, 'Dinner'), (7, 'Snack'), (8, 'Coffee'), (9, 'Tea'), (10, 'Wireless Internet'), (11, 'Close to school'), (12, 'Washer'), (13, 'Cable TV'), (14, 'TV'), (15, 'Kitchen')], max_length=35, verbose_name='Amenities options'),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Homestay'), (2, 'Live with a local host'), (3, 'Hostel'), (4, 'Shared Apartment'), (5, 'Private Apartment')], max_length=9, verbose_name='Type of Accommodation'),
        ),
        migrations.AlterField(
            model_name='workexchangeoption',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Accommodation'), (2, 'Discount in classes'), (6, 'Breakfast'), (7, 'Lunch'), (8, 'Dinner')], max_length=9, verbose_name='Work Exchange Categories'),
        ),
    ]
