# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 02:49
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20170324_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoption',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Private room'), (2, 'Shared room'), (3, 'Private bathroom'), (4, 'Breakfast'), (5, 'Lunch'), (6, 'Dinner'), (7, 'Snack'), (8, 'Coffee'), (9, 'Tea'), (10, 'Wireless Internet'), (11, 'Close to school'), (12, 'Washer'), (13, 'Cable TV'), (14, 'TV'), (15, 'Kitchen'), (16, 'Pool')], max_length=38, verbose_name='Amenities options'),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Wireless Internet'), (2, 'Laptop friendly workspace'), (3, 'Air conditioning'), (4, 'Heating'), (5, 'Breakfast'), (6, 'Lunch'), (7, 'Dinner'), (8, 'Snack'), (9, 'Coffee'), (10, 'Tea'), (11, 'Hammocks'), (12, 'Classrooms'), (13, 'Computers room'), (14, 'Video projector'), (15, 'Lounge area'), (16, 'Pool')], max_length=38, verbose_name='Amenities options'),
        ),
        migrations.AlterField(
            model_name='immersion',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Games and activities with local'), (2, 'Coffee tasting experience'), (3, 'Beer tasting experience'), (4, 'Chocolate tasting experience'), (5, 'Pub crawl'), (6, 'Local food tasting'), (7, 'Local dance class'), (8, 'Cooking Local Food'), (9, 'Local Movies Night')], max_length=17, verbose_name='Immersion options'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express'), (4, 'Paypal'), (5, 'Cash')], max_length=9, verbose_name='Payment Methods Accepted'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes_begin',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default='', max_length=13, verbose_name='Classes Begin'),
        ),
    ]
