# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20170405_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('VA', 'validated'), ('VE', 'verified')], default='VA', max_length=2),
        ),
    ]
