# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20170425_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='username',
            field=models.CharField(default='', help_text='School alias to use on url', max_length=100, verbose_name='Username'),
        ),
    ]
