# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 06:06
from __future__ import unicode_literals

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    for row in School.objects.all():
        row.alias_school = row.name.replace(' ', '-').lower() + '-' + str(row.id)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_alias_school'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
