# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.CharField(default='', help_text='Example: "colombia-immersion-school-2" (name splitted by - and id)', max_length=250, unique=True, verbose_name='Username'),
        ),
    ]
