# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 19:47
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20170426_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoption',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Private room'), (2, 'Shared room'), (3, 'Private bathroom'), (4, 'Breakfast'), (5, 'Lunch'), (6, 'Dinner'), (7, 'Snack'), (8, 'Coffee'), (9, 'Tea'), (10, 'Wireless Internet'), (11, 'Close to school'), (12, 'Washer'), (13, 'Cable TV'), (14, 'TV'), (15, 'Kitchen'), (16, 'Pool'), (17, '2 Beds'), (18, 'Shared bathroom')], max_length=44, verbose_name='Amenities options'),
        ),
    ]
