# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20170501_0201'),
        ('schools', '0015_auto_20170429_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
    ]
