# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 05:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='other_language_teach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), blank=True, help_text='Write each language, separated by commas', null=True, size=None, verbose_name='Other Languages Teach'),
        ),
    ]
