# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 20:17
from __future__ import unicode_literals

from random import randint

from django.db import migrations


def gen_views(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    for row in School.objects.all():
        row.views = randint(100, 250)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_views'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_views, reverse_code=migrations.RunPython.noop),
    ]
