# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='country',
            name='alias_country',
            field=models.CharField(default='', help_text='Example: "new-zealand" (name splitted by - )', max_length=250, unique=True, verbose_name='Alias Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(default='', max_length=200, verbose_name='Country English Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(default='', max_length=200, verbose_name='Country Spanish Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='photo',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Country Photo'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country Code'),
        ),
    ]
