# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20170501_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='thumbnail',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Country Thumbnail'),
        ),
    ]
