# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='country',
            name='description_es',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
