# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20170502_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='recommend',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='travellers recommend'),
        ),
    ]
