# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_country_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=200, verbose_name='Capital city'),
        ),
    ]
