# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_country_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='zone',
            field=models.CharField(blank=True, help_text='Look at country_zone.json on json_example folder (client project)', max_length=300, verbose_name='Country zone'),
        ),
    ]
